/* 
 * Engage Digital API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RingCentral.EngageDigital.Api;
using RingCentral.EngageDigital.Model;
using RingCentral.EngageDigital.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RingCentral.EngageDigital.Test
{
    /// <summary>
    ///  Class for testing Attachment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AttachmentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Attachment
        //private Attachment instance;

        public AttachmentTests()
        {
            // TODO uncomment below to create an instance of Attachment
            //instance = new Attachment();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Attachment
        /// </summary>
        [Fact]
        public void AttachmentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Attachment
            //Assert.IsInstanceOfType<Attachment> (instance, "variable 'instance' is a Attachment");
        }


        /// <summary>
        /// Test the property 'ContentType'
        /// </summary>
        [Fact]
        public void ContentTypeTest()
        {
            // TODO unit test for the property 'ContentType'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'Embed'
        /// </summary>
        [Fact]
        public void EmbedTest()
        {
            // TODO unit test for the property 'Embed'
        }
        /// <summary>
        /// Test the property 'Filename'
        /// </summary>
        [Fact]
        public void FilenameTest()
        {
            // TODO unit test for the property 'Filename'
        }
        /// <summary>
        /// Test the property 'ForeignId'
        /// </summary>
        [Fact]
        public void ForeignIdTest()
        {
            // TODO unit test for the property 'ForeignId'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Public'
        /// </summary>
        [Fact]
        public void PublicTest()
        {
            // TODO unit test for the property 'Public'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Fact]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'VideoMetadata'
        /// </summary>
        [Fact]
        public void VideoMetadataTest()
        {
            // TODO unit test for the property 'VideoMetadata'
        }

    }

}
