/* 
 * Engage Digital API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Engage.Digital.Client.Api;
using Engage.Digital.Model;
using Engage.Digital.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Engage.Digital.Api.Test
{
    /// <summary>
    ///  Class for testing GetAllThreadsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetAllThreadsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetAllThreadsResponse
        //private GetAllThreadsResponse instance;

        public GetAllThreadsResponseTests()
        {
            // TODO uncomment below to create an instance of GetAllThreadsResponse
            //instance = new GetAllThreadsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetAllThreadsResponse
        /// </summary>
        [Fact]
        public void GetAllThreadsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetAllThreadsResponse
            //Assert.IsInstanceOfType<GetAllThreadsResponse> (instance, "variable 'instance' is a GetAllThreadsResponse");
        }


        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Fact]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }
        /// <summary>
        /// Test the property 'Offset'
        /// </summary>
        [Fact]
        public void OffsetTest()
        {
            // TODO unit test for the property 'Offset'
        }
        /// <summary>
        /// Test the property 'Records'
        /// </summary>
        [Fact]
        public void RecordsTest()
        {
            // TODO unit test for the property 'Records'
        }

    }

}
