/* 
 * Engage Digital API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using RingCentral.EngageDigital.Client;
using RingCentral.EngageDigital.Model;

namespace RingCentral.EngageDigital.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IReplyAssistantEntriesApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Creating an entry
        /// </summary>
        /// <remarks>
        /// This method creates a reply assistant entry. In case of success it renders the entry, otherwise, it renders an error (422 HTTP code).  Authorization​: only users that have the right to manage reply assistant.
        /// </remarks>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="label">The name of the entry.</param>
        /// <returns>ReplyAssistantEntry</returns>
        ReplyAssistantEntry CreateReplyAssistantEntry (string label);

        /// <summary>
        /// Creating an entry
        /// </summary>
        /// <remarks>
        /// This method creates a reply assistant entry. In case of success it renders the entry, otherwise, it renders an error (422 HTTP code).  Authorization​: only users that have the right to manage reply assistant.
        /// </remarks>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="label">The name of the entry.</param>
        /// <returns>ApiResponse of ReplyAssistantEntry</returns>
        ApiResponse<ReplyAssistantEntry> CreateReplyAssistantEntryWithHttpInfo (string label);
        /// <summary>
        /// Deleting a reply assistant entry
        /// </summary>
        /// <remarks>
        /// This method destroys an existing entry. It renders the entry itself. It renders a 404 if id is invalid.  Authorization​: only users that have the right to manage reply assistant.
        /// </remarks>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="replyAssistantEntryId"></param>
        /// <returns>ReplyAssistantEntry</returns>
        ReplyAssistantEntry DeleteReplyAssistantEntry (string replyAssistantEntryId);

        /// <summary>
        /// Deleting a reply assistant entry
        /// </summary>
        /// <remarks>
        /// This method destroys an existing entry. It renders the entry itself. It renders a 404 if id is invalid.  Authorization​: only users that have the right to manage reply assistant.
        /// </remarks>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="replyAssistantEntryId"></param>
        /// <returns>ApiResponse of ReplyAssistantEntry</returns>
        ApiResponse<ReplyAssistantEntry> DeleteReplyAssistantEntryWithHttpInfo (string replyAssistantEntryId);
        /// <summary>
        /// Getting​ a​ll​ reply assistant e​ntries
        /// </summary>
        /// <remarks>
        /// This method renders all entries ordered by creation date (ascending).  Authorization​: only users that have the right to manage reply assistant.
        /// </remarks>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="offset">The record index to start. Default value is 0. (optional)</param>
        /// <param name="limit">The max number of records to return. Default value is 30, max value is 150. (optional)</param>
        /// <returns>GetAllReplyAssistantEntriesResponse</returns>
        GetAllReplyAssistantEntriesResponse GetAllReplyAssistantEntries (int? offset = default(int?), int? limit = default(int?));

        /// <summary>
        /// Getting​ a​ll​ reply assistant e​ntries
        /// </summary>
        /// <remarks>
        /// This method renders all entries ordered by creation date (ascending).  Authorization​: only users that have the right to manage reply assistant.
        /// </remarks>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="offset">The record index to start. Default value is 0. (optional)</param>
        /// <param name="limit">The max number of records to return. Default value is 30, max value is 150. (optional)</param>
        /// <returns>ApiResponse of GetAllReplyAssistantEntriesResponse</returns>
        ApiResponse<GetAllReplyAssistantEntriesResponse> GetAllReplyAssistantEntriesWithHttpInfo (int? offset = default(int?), int? limit = default(int?));
        /// <summary>
        /// Getting a reply assistant entry from its id
        /// </summary>
        /// <remarks>
        /// This method renders an entry from given id.  Authorization​: only users that have the right to manage reply assistant.
        /// </remarks>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="replyAssistantEntryId"></param>
        /// <returns>ReplyAssistantEntry</returns>
        ReplyAssistantEntry GetReplyAssistantEntry (string replyAssistantEntryId);

        /// <summary>
        /// Getting a reply assistant entry from its id
        /// </summary>
        /// <remarks>
        /// This method renders an entry from given id.  Authorization​: only users that have the right to manage reply assistant.
        /// </remarks>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="replyAssistantEntryId"></param>
        /// <returns>ApiResponse of ReplyAssistantEntry</returns>
        ApiResponse<ReplyAssistantEntry> GetReplyAssistantEntryWithHttpInfo (string replyAssistantEntryId);
        /// <summary>
        /// Updating a reply assistant entry
        /// </summary>
        /// <remarks>
        /// This method updates an existing entry from given attributes and renders it in case of success.  Authorization​: only users that have the right to manage reply assistant.
        /// </remarks>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="replyAssistantEntryId"></param>
        /// <param name="label">The name of the entry. (optional)</param>
        /// <param name="foreignId">The internal/company id of the entry. This is used to match Engage Digital entry’s id with the company one. Example: KB042. (optional)</param>
        /// <param name="categoryIds">To restrict the entry to a set of Engage Digital categories. Then, KB entries that do not match message’s categories to which you are replying will not be suggested. (optional)</param>
        /// <param name="shortcuts">entry shortcuts (optional)</param>
        /// <param name="entryGroupId">Entry group id. (optional)</param>
        /// <param name="sourceIds">Source ids (array) (optional)</param>
        /// <returns>ReplyAssistantEntry</returns>
        ReplyAssistantEntry UpdateReplyAssistantEntry (string replyAssistantEntryId, string label = default(string), string foreignId = default(string), Collection<string> categoryIds = default(Collection<string>), Collection<string> shortcuts = default(Collection<string>), string entryGroupId = default(string), Collection<string> sourceIds = default(Collection<string>));

        /// <summary>
        /// Updating a reply assistant entry
        /// </summary>
        /// <remarks>
        /// This method updates an existing entry from given attributes and renders it in case of success.  Authorization​: only users that have the right to manage reply assistant.
        /// </remarks>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="replyAssistantEntryId"></param>
        /// <param name="label">The name of the entry. (optional)</param>
        /// <param name="foreignId">The internal/company id of the entry. This is used to match Engage Digital entry’s id with the company one. Example: KB042. (optional)</param>
        /// <param name="categoryIds">To restrict the entry to a set of Engage Digital categories. Then, KB entries that do not match message’s categories to which you are replying will not be suggested. (optional)</param>
        /// <param name="shortcuts">entry shortcuts (optional)</param>
        /// <param name="entryGroupId">Entry group id. (optional)</param>
        /// <param name="sourceIds">Source ids (array) (optional)</param>
        /// <returns>ApiResponse of ReplyAssistantEntry</returns>
        ApiResponse<ReplyAssistantEntry> UpdateReplyAssistantEntryWithHttpInfo (string replyAssistantEntryId, string label = default(string), string foreignId = default(string), Collection<string> categoryIds = default(Collection<string>), Collection<string> shortcuts = default(Collection<string>), string entryGroupId = default(string), Collection<string> sourceIds = default(Collection<string>));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IReplyAssistantEntriesApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Creating an entry
        /// </summary>
        /// <remarks>
        /// This method creates a reply assistant entry. In case of success it renders the entry, otherwise, it renders an error (422 HTTP code).  Authorization​: only users that have the right to manage reply assistant.
        /// </remarks>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="label">The name of the entry.</param>
        /// <returns>Task of ReplyAssistantEntry</returns>
        System.Threading.Tasks.Task<ReplyAssistantEntry> CreateReplyAssistantEntryAsync (string label);

        /// <summary>
        /// Creating an entry
        /// </summary>
        /// <remarks>
        /// This method creates a reply assistant entry. In case of success it renders the entry, otherwise, it renders an error (422 HTTP code).  Authorization​: only users that have the right to manage reply assistant.
        /// </remarks>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="label">The name of the entry.</param>
        /// <returns>Task of ApiResponse (ReplyAssistantEntry)</returns>
        System.Threading.Tasks.Task<ApiResponse<ReplyAssistantEntry>> CreateReplyAssistantEntryAsyncWithHttpInfo (string label);
        /// <summary>
        /// Deleting a reply assistant entry
        /// </summary>
        /// <remarks>
        /// This method destroys an existing entry. It renders the entry itself. It renders a 404 if id is invalid.  Authorization​: only users that have the right to manage reply assistant.
        /// </remarks>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="replyAssistantEntryId"></param>
        /// <returns>Task of ReplyAssistantEntry</returns>
        System.Threading.Tasks.Task<ReplyAssistantEntry> DeleteReplyAssistantEntryAsync (string replyAssistantEntryId);

        /// <summary>
        /// Deleting a reply assistant entry
        /// </summary>
        /// <remarks>
        /// This method destroys an existing entry. It renders the entry itself. It renders a 404 if id is invalid.  Authorization​: only users that have the right to manage reply assistant.
        /// </remarks>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="replyAssistantEntryId"></param>
        /// <returns>Task of ApiResponse (ReplyAssistantEntry)</returns>
        System.Threading.Tasks.Task<ApiResponse<ReplyAssistantEntry>> DeleteReplyAssistantEntryAsyncWithHttpInfo (string replyAssistantEntryId);
        /// <summary>
        /// Getting​ a​ll​ reply assistant e​ntries
        /// </summary>
        /// <remarks>
        /// This method renders all entries ordered by creation date (ascending).  Authorization​: only users that have the right to manage reply assistant.
        /// </remarks>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="offset">The record index to start. Default value is 0. (optional)</param>
        /// <param name="limit">The max number of records to return. Default value is 30, max value is 150. (optional)</param>
        /// <returns>Task of GetAllReplyAssistantEntriesResponse</returns>
        System.Threading.Tasks.Task<GetAllReplyAssistantEntriesResponse> GetAllReplyAssistantEntriesAsync (int? offset = default(int?), int? limit = default(int?));

        /// <summary>
        /// Getting​ a​ll​ reply assistant e​ntries
        /// </summary>
        /// <remarks>
        /// This method renders all entries ordered by creation date (ascending).  Authorization​: only users that have the right to manage reply assistant.
        /// </remarks>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="offset">The record index to start. Default value is 0. (optional)</param>
        /// <param name="limit">The max number of records to return. Default value is 30, max value is 150. (optional)</param>
        /// <returns>Task of ApiResponse (GetAllReplyAssistantEntriesResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetAllReplyAssistantEntriesResponse>> GetAllReplyAssistantEntriesAsyncWithHttpInfo (int? offset = default(int?), int? limit = default(int?));
        /// <summary>
        /// Getting a reply assistant entry from its id
        /// </summary>
        /// <remarks>
        /// This method renders an entry from given id.  Authorization​: only users that have the right to manage reply assistant.
        /// </remarks>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="replyAssistantEntryId"></param>
        /// <returns>Task of ReplyAssistantEntry</returns>
        System.Threading.Tasks.Task<ReplyAssistantEntry> GetReplyAssistantEntryAsync (string replyAssistantEntryId);

        /// <summary>
        /// Getting a reply assistant entry from its id
        /// </summary>
        /// <remarks>
        /// This method renders an entry from given id.  Authorization​: only users that have the right to manage reply assistant.
        /// </remarks>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="replyAssistantEntryId"></param>
        /// <returns>Task of ApiResponse (ReplyAssistantEntry)</returns>
        System.Threading.Tasks.Task<ApiResponse<ReplyAssistantEntry>> GetReplyAssistantEntryAsyncWithHttpInfo (string replyAssistantEntryId);
        /// <summary>
        /// Updating a reply assistant entry
        /// </summary>
        /// <remarks>
        /// This method updates an existing entry from given attributes and renders it in case of success.  Authorization​: only users that have the right to manage reply assistant.
        /// </remarks>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="replyAssistantEntryId"></param>
        /// <param name="label">The name of the entry. (optional)</param>
        /// <param name="foreignId">The internal/company id of the entry. This is used to match Engage Digital entry’s id with the company one. Example: KB042. (optional)</param>
        /// <param name="categoryIds">To restrict the entry to a set of Engage Digital categories. Then, KB entries that do not match message’s categories to which you are replying will not be suggested. (optional)</param>
        /// <param name="shortcuts">entry shortcuts (optional)</param>
        /// <param name="entryGroupId">Entry group id. (optional)</param>
        /// <param name="sourceIds">Source ids (array) (optional)</param>
        /// <returns>Task of ReplyAssistantEntry</returns>
        System.Threading.Tasks.Task<ReplyAssistantEntry> UpdateReplyAssistantEntryAsync (string replyAssistantEntryId, string label = default(string), string foreignId = default(string), Collection<string> categoryIds = default(Collection<string>), Collection<string> shortcuts = default(Collection<string>), string entryGroupId = default(string), Collection<string> sourceIds = default(Collection<string>));

        /// <summary>
        /// Updating a reply assistant entry
        /// </summary>
        /// <remarks>
        /// This method updates an existing entry from given attributes and renders it in case of success.  Authorization​: only users that have the right to manage reply assistant.
        /// </remarks>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="replyAssistantEntryId"></param>
        /// <param name="label">The name of the entry. (optional)</param>
        /// <param name="foreignId">The internal/company id of the entry. This is used to match Engage Digital entry’s id with the company one. Example: KB042. (optional)</param>
        /// <param name="categoryIds">To restrict the entry to a set of Engage Digital categories. Then, KB entries that do not match message’s categories to which you are replying will not be suggested. (optional)</param>
        /// <param name="shortcuts">entry shortcuts (optional)</param>
        /// <param name="entryGroupId">Entry group id. (optional)</param>
        /// <param name="sourceIds">Source ids (array) (optional)</param>
        /// <returns>Task of ApiResponse (ReplyAssistantEntry)</returns>
        System.Threading.Tasks.Task<ApiResponse<ReplyAssistantEntry>> UpdateReplyAssistantEntryAsyncWithHttpInfo (string replyAssistantEntryId, string label = default(string), string foreignId = default(string), Collection<string> categoryIds = default(Collection<string>), Collection<string> shortcuts = default(Collection<string>), string entryGroupId = default(string), Collection<string> sourceIds = default(Collection<string>));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IReplyAssistantEntriesApi : IReplyAssistantEntriesApiSync, IReplyAssistantEntriesApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ReplyAssistantEntriesApi : IReplyAssistantEntriesApi
    {
        private RingCentral.EngageDigital.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ReplyAssistantEntriesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ReplyAssistantEntriesApi() : this((string) null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReplyAssistantEntriesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ReplyAssistantEntriesApi(String basePath)
        {
            this.Configuration = RingCentral.EngageDigital.Client.Configuration.MergeConfigurations(
                RingCentral.EngageDigital.Client.GlobalConfiguration.Instance,
                new RingCentral.EngageDigital.Client.Configuration { BasePath = basePath }
            );
            this.Client = new RingCentral.EngageDigital.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new RingCentral.EngageDigital.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = RingCentral.EngageDigital.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReplyAssistantEntriesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ReplyAssistantEntriesApi(RingCentral.EngageDigital.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = RingCentral.EngageDigital.Client.Configuration.MergeConfigurations(
                RingCentral.EngageDigital.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new RingCentral.EngageDigital.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new RingCentral.EngageDigital.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = RingCentral.EngageDigital.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReplyAssistantEntriesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public ReplyAssistantEntriesApi(RingCentral.EngageDigital.Client.ISynchronousClient client,RingCentral.EngageDigital.Client.IAsynchronousClient asyncClient, RingCentral.EngageDigital.Client.IReadableConfiguration configuration)
        {
            if(client == null) throw new ArgumentNullException("client");
            if(asyncClient == null) throw new ArgumentNullException("asyncClient");
            if(configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = RingCentral.EngageDigital.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public RingCentral.EngageDigital.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public RingCentral.EngageDigital.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public RingCentral.EngageDigital.Client.IReadableConfiguration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public RingCentral.EngageDigital.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Creating an entry This method creates a reply assistant entry. In case of success it renders the entry, otherwise, it renders an error (422 HTTP code).  Authorization​: only users that have the right to manage reply assistant.
        /// </summary>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="label">The name of the entry.</param>
        /// <returns>ReplyAssistantEntry</returns>
        public ReplyAssistantEntry CreateReplyAssistantEntry (string label)
        {
             RingCentral.EngageDigital.Client.ApiResponse<ReplyAssistantEntry> localVarResponse = CreateReplyAssistantEntryWithHttpInfo(label);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Creating an entry This method creates a reply assistant entry. In case of success it renders the entry, otherwise, it renders an error (422 HTTP code).  Authorization​: only users that have the right to manage reply assistant.
        /// </summary>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="label">The name of the entry.</param>
        /// <returns>ApiResponse of ReplyAssistantEntry</returns>
        public RingCentral.EngageDigital.Client.ApiResponse< ReplyAssistantEntry > CreateReplyAssistantEntryWithHttpInfo (string label)
        {
            // verify the required parameter 'label' is set
            if (label == null)
                throw new RingCentral.EngageDigital.Client.ApiException(400, "Missing required parameter 'label' when calling ReplyAssistantEntriesApi->CreateReplyAssistantEntry");

            RingCentral.EngageDigital.Client.RequestOptions localVarRequestOptions = new RingCentral.EngageDigital.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = RingCentral.EngageDigital.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = RingCentral.EngageDigital.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (label != null)
            {
                foreach (var _kvp in RingCentral.EngageDigital.Client.ClientUtils.ParameterToMultiMap("", "label", label))
                {
                    foreach (var _kvpValue in _kvp.Value)
                    {
                        localVarRequestOptions.QueryParameters.Add(_kvp.Key, _kvpValue);
                    }
                }
            }


            // make the HTTP request
            var localVarResponse = this.Client.Post< ReplyAssistantEntry >("/reply_assistant/entries", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateReplyAssistantEntry", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Creating an entry This method creates a reply assistant entry. In case of success it renders the entry, otherwise, it renders an error (422 HTTP code).  Authorization​: only users that have the right to manage reply assistant.
        /// </summary>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="label">The name of the entry.</param>
        /// <returns>Task of ReplyAssistantEntry</returns>
        public async System.Threading.Tasks.Task<ReplyAssistantEntry> CreateReplyAssistantEntryAsync (string label)
        {
             RingCentral.EngageDigital.Client.ApiResponse<ReplyAssistantEntry> localVarResponse = await CreateReplyAssistantEntryAsyncWithHttpInfo(label);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Creating an entry This method creates a reply assistant entry. In case of success it renders the entry, otherwise, it renders an error (422 HTTP code).  Authorization​: only users that have the right to manage reply assistant.
        /// </summary>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="label">The name of the entry.</param>
        /// <returns>Task of ApiResponse (ReplyAssistantEntry)</returns>
        public async System.Threading.Tasks.Task<RingCentral.EngageDigital.Client.ApiResponse<ReplyAssistantEntry>> CreateReplyAssistantEntryAsyncWithHttpInfo (string label)
        {
            // verify the required parameter 'label' is set
            if (label == null)
                throw new RingCentral.EngageDigital.Client.ApiException(400, "Missing required parameter 'label' when calling ReplyAssistantEntriesApi->CreateReplyAssistantEntry");


            RingCentral.EngageDigital.Client.RequestOptions localVarRequestOptions = new RingCentral.EngageDigital.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (label != null)
            {
                foreach (var _kvp in RingCentral.EngageDigital.Client.ClientUtils.ParameterToMultiMap("", "label", label))
                {
                    foreach (var _kvpValue in _kvp.Value)
                    {
                        localVarRequestOptions.QueryParameters.Add(_kvp.Key, _kvpValue);
                    }
                }
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<ReplyAssistantEntry>("/reply_assistant/entries", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateReplyAssistantEntry", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Deleting a reply assistant entry This method destroys an existing entry. It renders the entry itself. It renders a 404 if id is invalid.  Authorization​: only users that have the right to manage reply assistant.
        /// </summary>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="replyAssistantEntryId"></param>
        /// <returns>ReplyAssistantEntry</returns>
        public ReplyAssistantEntry DeleteReplyAssistantEntry (string replyAssistantEntryId)
        {
             RingCentral.EngageDigital.Client.ApiResponse<ReplyAssistantEntry> localVarResponse = DeleteReplyAssistantEntryWithHttpInfo(replyAssistantEntryId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Deleting a reply assistant entry This method destroys an existing entry. It renders the entry itself. It renders a 404 if id is invalid.  Authorization​: only users that have the right to manage reply assistant.
        /// </summary>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="replyAssistantEntryId"></param>
        /// <returns>ApiResponse of ReplyAssistantEntry</returns>
        public RingCentral.EngageDigital.Client.ApiResponse< ReplyAssistantEntry > DeleteReplyAssistantEntryWithHttpInfo (string replyAssistantEntryId)
        {
            // verify the required parameter 'replyAssistantEntryId' is set
            if (replyAssistantEntryId == null)
                throw new RingCentral.EngageDigital.Client.ApiException(400, "Missing required parameter 'replyAssistantEntryId' when calling ReplyAssistantEntriesApi->DeleteReplyAssistantEntry");

            RingCentral.EngageDigital.Client.RequestOptions localVarRequestOptions = new RingCentral.EngageDigital.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = RingCentral.EngageDigital.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = RingCentral.EngageDigital.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (replyAssistantEntryId != null)
                localVarRequestOptions.PathParameters.Add("replyAssistantEntryId", RingCentral.EngageDigital.Client.ClientUtils.ParameterToString(replyAssistantEntryId)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Delete< ReplyAssistantEntry >("/reply_assistant/entries/{replyAssistantEntryId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteReplyAssistantEntry", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Deleting a reply assistant entry This method destroys an existing entry. It renders the entry itself. It renders a 404 if id is invalid.  Authorization​: only users that have the right to manage reply assistant.
        /// </summary>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="replyAssistantEntryId"></param>
        /// <returns>Task of ReplyAssistantEntry</returns>
        public async System.Threading.Tasks.Task<ReplyAssistantEntry> DeleteReplyAssistantEntryAsync (string replyAssistantEntryId)
        {
             RingCentral.EngageDigital.Client.ApiResponse<ReplyAssistantEntry> localVarResponse = await DeleteReplyAssistantEntryAsyncWithHttpInfo(replyAssistantEntryId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Deleting a reply assistant entry This method destroys an existing entry. It renders the entry itself. It renders a 404 if id is invalid.  Authorization​: only users that have the right to manage reply assistant.
        /// </summary>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="replyAssistantEntryId"></param>
        /// <returns>Task of ApiResponse (ReplyAssistantEntry)</returns>
        public async System.Threading.Tasks.Task<RingCentral.EngageDigital.Client.ApiResponse<ReplyAssistantEntry>> DeleteReplyAssistantEntryAsyncWithHttpInfo (string replyAssistantEntryId)
        {
            // verify the required parameter 'replyAssistantEntryId' is set
            if (replyAssistantEntryId == null)
                throw new RingCentral.EngageDigital.Client.ApiException(400, "Missing required parameter 'replyAssistantEntryId' when calling ReplyAssistantEntriesApi->DeleteReplyAssistantEntry");


            RingCentral.EngageDigital.Client.RequestOptions localVarRequestOptions = new RingCentral.EngageDigital.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (replyAssistantEntryId != null)
                localVarRequestOptions.PathParameters.Add("replyAssistantEntryId", RingCentral.EngageDigital.Client.ClientUtils.ParameterToString(replyAssistantEntryId)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<ReplyAssistantEntry>("/reply_assistant/entries/{replyAssistantEntryId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteReplyAssistantEntry", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Getting​ a​ll​ reply assistant e​ntries This method renders all entries ordered by creation date (ascending).  Authorization​: only users that have the right to manage reply assistant.
        /// </summary>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="offset">The record index to start. Default value is 0. (optional)</param>
        /// <param name="limit">The max number of records to return. Default value is 30, max value is 150. (optional)</param>
        /// <returns>GetAllReplyAssistantEntriesResponse</returns>
        public GetAllReplyAssistantEntriesResponse GetAllReplyAssistantEntries (int? offset = default(int?), int? limit = default(int?))
        {
             RingCentral.EngageDigital.Client.ApiResponse<GetAllReplyAssistantEntriesResponse> localVarResponse = GetAllReplyAssistantEntriesWithHttpInfo(offset, limit);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Getting​ a​ll​ reply assistant e​ntries This method renders all entries ordered by creation date (ascending).  Authorization​: only users that have the right to manage reply assistant.
        /// </summary>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="offset">The record index to start. Default value is 0. (optional)</param>
        /// <param name="limit">The max number of records to return. Default value is 30, max value is 150. (optional)</param>
        /// <returns>ApiResponse of GetAllReplyAssistantEntriesResponse</returns>
        public RingCentral.EngageDigital.Client.ApiResponse< GetAllReplyAssistantEntriesResponse > GetAllReplyAssistantEntriesWithHttpInfo (int? offset = default(int?), int? limit = default(int?))
        {
            RingCentral.EngageDigital.Client.RequestOptions localVarRequestOptions = new RingCentral.EngageDigital.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = RingCentral.EngageDigital.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = RingCentral.EngageDigital.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (offset != null)
            {
                foreach (var _kvp in RingCentral.EngageDigital.Client.ClientUtils.ParameterToMultiMap("", "offset", offset))
                {
                    foreach (var _kvpValue in _kvp.Value)
                    {
                        localVarRequestOptions.QueryParameters.Add(_kvp.Key, _kvpValue);
                    }
                }
            }
            if (limit != null)
            {
                foreach (var _kvp in RingCentral.EngageDigital.Client.ClientUtils.ParameterToMultiMap("", "limit", limit))
                {
                    foreach (var _kvpValue in _kvp.Value)
                    {
                        localVarRequestOptions.QueryParameters.Add(_kvp.Key, _kvpValue);
                    }
                }
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get< GetAllReplyAssistantEntriesResponse >("/reply_assistant/entries", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAllReplyAssistantEntries", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Getting​ a​ll​ reply assistant e​ntries This method renders all entries ordered by creation date (ascending).  Authorization​: only users that have the right to manage reply assistant.
        /// </summary>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="offset">The record index to start. Default value is 0. (optional)</param>
        /// <param name="limit">The max number of records to return. Default value is 30, max value is 150. (optional)</param>
        /// <returns>Task of GetAllReplyAssistantEntriesResponse</returns>
        public async System.Threading.Tasks.Task<GetAllReplyAssistantEntriesResponse> GetAllReplyAssistantEntriesAsync (int? offset = default(int?), int? limit = default(int?))
        {
             RingCentral.EngageDigital.Client.ApiResponse<GetAllReplyAssistantEntriesResponse> localVarResponse = await GetAllReplyAssistantEntriesAsyncWithHttpInfo(offset, limit);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Getting​ a​ll​ reply assistant e​ntries This method renders all entries ordered by creation date (ascending).  Authorization​: only users that have the right to manage reply assistant.
        /// </summary>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="offset">The record index to start. Default value is 0. (optional)</param>
        /// <param name="limit">The max number of records to return. Default value is 30, max value is 150. (optional)</param>
        /// <returns>Task of ApiResponse (GetAllReplyAssistantEntriesResponse)</returns>
        public async System.Threading.Tasks.Task<RingCentral.EngageDigital.Client.ApiResponse<GetAllReplyAssistantEntriesResponse>> GetAllReplyAssistantEntriesAsyncWithHttpInfo (int? offset = default(int?), int? limit = default(int?))
        {

            RingCentral.EngageDigital.Client.RequestOptions localVarRequestOptions = new RingCentral.EngageDigital.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (offset != null)
            {
                foreach (var _kvp in RingCentral.EngageDigital.Client.ClientUtils.ParameterToMultiMap("", "offset", offset))
                {
                    foreach (var _kvpValue in _kvp.Value)
                    {
                        localVarRequestOptions.QueryParameters.Add(_kvp.Key, _kvpValue);
                    }
                }
            }
            if (limit != null)
            {
                foreach (var _kvp in RingCentral.EngageDigital.Client.ClientUtils.ParameterToMultiMap("", "limit", limit))
                {
                    foreach (var _kvpValue in _kvp.Value)
                    {
                        localVarRequestOptions.QueryParameters.Add(_kvp.Key, _kvpValue);
                    }
                }
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<GetAllReplyAssistantEntriesResponse>("/reply_assistant/entries", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAllReplyAssistantEntries", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Getting a reply assistant entry from its id This method renders an entry from given id.  Authorization​: only users that have the right to manage reply assistant.
        /// </summary>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="replyAssistantEntryId"></param>
        /// <returns>ReplyAssistantEntry</returns>
        public ReplyAssistantEntry GetReplyAssistantEntry (string replyAssistantEntryId)
        {
             RingCentral.EngageDigital.Client.ApiResponse<ReplyAssistantEntry> localVarResponse = GetReplyAssistantEntryWithHttpInfo(replyAssistantEntryId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Getting a reply assistant entry from its id This method renders an entry from given id.  Authorization​: only users that have the right to manage reply assistant.
        /// </summary>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="replyAssistantEntryId"></param>
        /// <returns>ApiResponse of ReplyAssistantEntry</returns>
        public RingCentral.EngageDigital.Client.ApiResponse< ReplyAssistantEntry > GetReplyAssistantEntryWithHttpInfo (string replyAssistantEntryId)
        {
            // verify the required parameter 'replyAssistantEntryId' is set
            if (replyAssistantEntryId == null)
                throw new RingCentral.EngageDigital.Client.ApiException(400, "Missing required parameter 'replyAssistantEntryId' when calling ReplyAssistantEntriesApi->GetReplyAssistantEntry");

            RingCentral.EngageDigital.Client.RequestOptions localVarRequestOptions = new RingCentral.EngageDigital.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = RingCentral.EngageDigital.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = RingCentral.EngageDigital.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (replyAssistantEntryId != null)
                localVarRequestOptions.PathParameters.Add("replyAssistantEntryId", RingCentral.EngageDigital.Client.ClientUtils.ParameterToString(replyAssistantEntryId)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get< ReplyAssistantEntry >("/reply_assistant/entries/{replyAssistantEntryId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetReplyAssistantEntry", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Getting a reply assistant entry from its id This method renders an entry from given id.  Authorization​: only users that have the right to manage reply assistant.
        /// </summary>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="replyAssistantEntryId"></param>
        /// <returns>Task of ReplyAssistantEntry</returns>
        public async System.Threading.Tasks.Task<ReplyAssistantEntry> GetReplyAssistantEntryAsync (string replyAssistantEntryId)
        {
             RingCentral.EngageDigital.Client.ApiResponse<ReplyAssistantEntry> localVarResponse = await GetReplyAssistantEntryAsyncWithHttpInfo(replyAssistantEntryId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Getting a reply assistant entry from its id This method renders an entry from given id.  Authorization​: only users that have the right to manage reply assistant.
        /// </summary>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="replyAssistantEntryId"></param>
        /// <returns>Task of ApiResponse (ReplyAssistantEntry)</returns>
        public async System.Threading.Tasks.Task<RingCentral.EngageDigital.Client.ApiResponse<ReplyAssistantEntry>> GetReplyAssistantEntryAsyncWithHttpInfo (string replyAssistantEntryId)
        {
            // verify the required parameter 'replyAssistantEntryId' is set
            if (replyAssistantEntryId == null)
                throw new RingCentral.EngageDigital.Client.ApiException(400, "Missing required parameter 'replyAssistantEntryId' when calling ReplyAssistantEntriesApi->GetReplyAssistantEntry");


            RingCentral.EngageDigital.Client.RequestOptions localVarRequestOptions = new RingCentral.EngageDigital.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (replyAssistantEntryId != null)
                localVarRequestOptions.PathParameters.Add("replyAssistantEntryId", RingCentral.EngageDigital.Client.ClientUtils.ParameterToString(replyAssistantEntryId)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ReplyAssistantEntry>("/reply_assistant/entries/{replyAssistantEntryId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetReplyAssistantEntry", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Updating a reply assistant entry This method updates an existing entry from given attributes and renders it in case of success.  Authorization​: only users that have the right to manage reply assistant.
        /// </summary>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="replyAssistantEntryId"></param>
        /// <param name="label">The name of the entry. (optional)</param>
        /// <param name="foreignId">The internal/company id of the entry. This is used to match Engage Digital entry’s id with the company one. Example: KB042. (optional)</param>
        /// <param name="categoryIds">To restrict the entry to a set of Engage Digital categories. Then, KB entries that do not match message’s categories to which you are replying will not be suggested. (optional)</param>
        /// <param name="shortcuts">entry shortcuts (optional)</param>
        /// <param name="entryGroupId">Entry group id. (optional)</param>
        /// <param name="sourceIds">Source ids (array) (optional)</param>
        /// <returns>ReplyAssistantEntry</returns>
        public ReplyAssistantEntry UpdateReplyAssistantEntry (string replyAssistantEntryId, string label = default(string), string foreignId = default(string), Collection<string> categoryIds = default(Collection<string>), Collection<string> shortcuts = default(Collection<string>), string entryGroupId = default(string), Collection<string> sourceIds = default(Collection<string>))
        {
             RingCentral.EngageDigital.Client.ApiResponse<ReplyAssistantEntry> localVarResponse = UpdateReplyAssistantEntryWithHttpInfo(replyAssistantEntryId, label, foreignId, categoryIds, shortcuts, entryGroupId, sourceIds);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Updating a reply assistant entry This method updates an existing entry from given attributes and renders it in case of success.  Authorization​: only users that have the right to manage reply assistant.
        /// </summary>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="replyAssistantEntryId"></param>
        /// <param name="label">The name of the entry. (optional)</param>
        /// <param name="foreignId">The internal/company id of the entry. This is used to match Engage Digital entry’s id with the company one. Example: KB042. (optional)</param>
        /// <param name="categoryIds">To restrict the entry to a set of Engage Digital categories. Then, KB entries that do not match message’s categories to which you are replying will not be suggested. (optional)</param>
        /// <param name="shortcuts">entry shortcuts (optional)</param>
        /// <param name="entryGroupId">Entry group id. (optional)</param>
        /// <param name="sourceIds">Source ids (array) (optional)</param>
        /// <returns>ApiResponse of ReplyAssistantEntry</returns>
        public RingCentral.EngageDigital.Client.ApiResponse< ReplyAssistantEntry > UpdateReplyAssistantEntryWithHttpInfo (string replyAssistantEntryId, string label = default(string), string foreignId = default(string), Collection<string> categoryIds = default(Collection<string>), Collection<string> shortcuts = default(Collection<string>), string entryGroupId = default(string), Collection<string> sourceIds = default(Collection<string>))
        {
            // verify the required parameter 'replyAssistantEntryId' is set
            if (replyAssistantEntryId == null)
                throw new RingCentral.EngageDigital.Client.ApiException(400, "Missing required parameter 'replyAssistantEntryId' when calling ReplyAssistantEntriesApi->UpdateReplyAssistantEntry");

            RingCentral.EngageDigital.Client.RequestOptions localVarRequestOptions = new RingCentral.EngageDigital.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = RingCentral.EngageDigital.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = RingCentral.EngageDigital.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (replyAssistantEntryId != null)
                localVarRequestOptions.PathParameters.Add("replyAssistantEntryId", RingCentral.EngageDigital.Client.ClientUtils.ParameterToString(replyAssistantEntryId)); // path parameter
            if (label != null)
            {
                foreach (var _kvp in RingCentral.EngageDigital.Client.ClientUtils.ParameterToMultiMap("", "label", label))
                {
                    foreach (var _kvpValue in _kvp.Value)
                    {
                        localVarRequestOptions.QueryParameters.Add(_kvp.Key, _kvpValue);
                    }
                }
            }
            if (foreignId != null)
            {
                foreach (var _kvp in RingCentral.EngageDigital.Client.ClientUtils.ParameterToMultiMap("", "foreign_id", foreignId))
                {
                    foreach (var _kvpValue in _kvp.Value)
                    {
                        localVarRequestOptions.QueryParameters.Add(_kvp.Key, _kvpValue);
                    }
                }
            }
            if (categoryIds != null)
            {
                foreach (var _kvp in RingCentral.EngageDigital.Client.ClientUtils.ParameterToMultiMap("multi", "category_ids[]", categoryIds))
                {
                    foreach (var _kvpValue in _kvp.Value)
                    {
                        localVarRequestOptions.QueryParameters.Add(_kvp.Key, _kvpValue);
                    }
                }
            }
            if (shortcuts != null)
            {
                foreach (var _kvp in RingCentral.EngageDigital.Client.ClientUtils.ParameterToMultiMap("multi", "shortcuts[]", shortcuts))
                {
                    foreach (var _kvpValue in _kvp.Value)
                    {
                        localVarRequestOptions.QueryParameters.Add(_kvp.Key, _kvpValue);
                    }
                }
            }
            if (entryGroupId != null)
            {
                foreach (var _kvp in RingCentral.EngageDigital.Client.ClientUtils.ParameterToMultiMap("", "entry_group_id", entryGroupId))
                {
                    foreach (var _kvpValue in _kvp.Value)
                    {
                        localVarRequestOptions.QueryParameters.Add(_kvp.Key, _kvpValue);
                    }
                }
            }
            if (sourceIds != null)
            {
                foreach (var _kvp in RingCentral.EngageDigital.Client.ClientUtils.ParameterToMultiMap("multi", "source_ids[]", sourceIds))
                {
                    foreach (var _kvpValue in _kvp.Value)
                    {
                        localVarRequestOptions.QueryParameters.Add(_kvp.Key, _kvpValue);
                    }
                }
            }


            // make the HTTP request
            var localVarResponse = this.Client.Put< ReplyAssistantEntry >("/reply_assistant/entries/{replyAssistantEntryId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateReplyAssistantEntry", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Updating a reply assistant entry This method updates an existing entry from given attributes and renders it in case of success.  Authorization​: only users that have the right to manage reply assistant.
        /// </summary>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="replyAssistantEntryId"></param>
        /// <param name="label">The name of the entry. (optional)</param>
        /// <param name="foreignId">The internal/company id of the entry. This is used to match Engage Digital entry’s id with the company one. Example: KB042. (optional)</param>
        /// <param name="categoryIds">To restrict the entry to a set of Engage Digital categories. Then, KB entries that do not match message’s categories to which you are replying will not be suggested. (optional)</param>
        /// <param name="shortcuts">entry shortcuts (optional)</param>
        /// <param name="entryGroupId">Entry group id. (optional)</param>
        /// <param name="sourceIds">Source ids (array) (optional)</param>
        /// <returns>Task of ReplyAssistantEntry</returns>
        public async System.Threading.Tasks.Task<ReplyAssistantEntry> UpdateReplyAssistantEntryAsync (string replyAssistantEntryId, string label = default(string), string foreignId = default(string), Collection<string> categoryIds = default(Collection<string>), Collection<string> shortcuts = default(Collection<string>), string entryGroupId = default(string), Collection<string> sourceIds = default(Collection<string>))
        {
             RingCentral.EngageDigital.Client.ApiResponse<ReplyAssistantEntry> localVarResponse = await UpdateReplyAssistantEntryAsyncWithHttpInfo(replyAssistantEntryId, label, foreignId, categoryIds, shortcuts, entryGroupId, sourceIds);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Updating a reply assistant entry This method updates an existing entry from given attributes and renders it in case of success.  Authorization​: only users that have the right to manage reply assistant.
        /// </summary>
        /// <exception cref="RingCentral.EngageDigital.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="replyAssistantEntryId"></param>
        /// <param name="label">The name of the entry. (optional)</param>
        /// <param name="foreignId">The internal/company id of the entry. This is used to match Engage Digital entry’s id with the company one. Example: KB042. (optional)</param>
        /// <param name="categoryIds">To restrict the entry to a set of Engage Digital categories. Then, KB entries that do not match message’s categories to which you are replying will not be suggested. (optional)</param>
        /// <param name="shortcuts">entry shortcuts (optional)</param>
        /// <param name="entryGroupId">Entry group id. (optional)</param>
        /// <param name="sourceIds">Source ids (array) (optional)</param>
        /// <returns>Task of ApiResponse (ReplyAssistantEntry)</returns>
        public async System.Threading.Tasks.Task<RingCentral.EngageDigital.Client.ApiResponse<ReplyAssistantEntry>> UpdateReplyAssistantEntryAsyncWithHttpInfo (string replyAssistantEntryId, string label = default(string), string foreignId = default(string), Collection<string> categoryIds = default(Collection<string>), Collection<string> shortcuts = default(Collection<string>), string entryGroupId = default(string), Collection<string> sourceIds = default(Collection<string>))
        {
            // verify the required parameter 'replyAssistantEntryId' is set
            if (replyAssistantEntryId == null)
                throw new RingCentral.EngageDigital.Client.ApiException(400, "Missing required parameter 'replyAssistantEntryId' when calling ReplyAssistantEntriesApi->UpdateReplyAssistantEntry");


            RingCentral.EngageDigital.Client.RequestOptions localVarRequestOptions = new RingCentral.EngageDigital.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (replyAssistantEntryId != null)
                localVarRequestOptions.PathParameters.Add("replyAssistantEntryId", RingCentral.EngageDigital.Client.ClientUtils.ParameterToString(replyAssistantEntryId)); // path parameter
            if (label != null)
            {
                foreach (var _kvp in RingCentral.EngageDigital.Client.ClientUtils.ParameterToMultiMap("", "label", label))
                {
                    foreach (var _kvpValue in _kvp.Value)
                    {
                        localVarRequestOptions.QueryParameters.Add(_kvp.Key, _kvpValue);
                    }
                }
            }
            if (foreignId != null)
            {
                foreach (var _kvp in RingCentral.EngageDigital.Client.ClientUtils.ParameterToMultiMap("", "foreign_id", foreignId))
                {
                    foreach (var _kvpValue in _kvp.Value)
                    {
                        localVarRequestOptions.QueryParameters.Add(_kvp.Key, _kvpValue);
                    }
                }
            }
            if (categoryIds != null)
            {
                foreach (var _kvp in RingCentral.EngageDigital.Client.ClientUtils.ParameterToMultiMap("multi", "category_ids[]", categoryIds))
                {
                    foreach (var _kvpValue in _kvp.Value)
                    {
                        localVarRequestOptions.QueryParameters.Add(_kvp.Key, _kvpValue);
                    }
                }
            }
            if (shortcuts != null)
            {
                foreach (var _kvp in RingCentral.EngageDigital.Client.ClientUtils.ParameterToMultiMap("multi", "shortcuts[]", shortcuts))
                {
                    foreach (var _kvpValue in _kvp.Value)
                    {
                        localVarRequestOptions.QueryParameters.Add(_kvp.Key, _kvpValue);
                    }
                }
            }
            if (entryGroupId != null)
            {
                foreach (var _kvp in RingCentral.EngageDigital.Client.ClientUtils.ParameterToMultiMap("", "entry_group_id", entryGroupId))
                {
                    foreach (var _kvpValue in _kvp.Value)
                    {
                        localVarRequestOptions.QueryParameters.Add(_kvp.Key, _kvpValue);
                    }
                }
            }
            if (sourceIds != null)
            {
                foreach (var _kvp in RingCentral.EngageDigital.Client.ClientUtils.ParameterToMultiMap("multi", "source_ids[]", sourceIds))
                {
                    foreach (var _kvpValue in _kvp.Value)
                    {
                        localVarRequestOptions.QueryParameters.Add(_kvp.Key, _kvpValue);
                    }
                }
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PutAsync<ReplyAssistantEntry>("/reply_assistant/entries/{replyAssistantEntryId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateReplyAssistantEntry", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
