/* 
 * Engage Digital API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using RingCentral.EngageDigital.Client;
using RingCentral.EngageDigital.Api;
using RingCentral.EngageDigital.Model;

namespace RingCentral.Engage.Test
{
    /// <summary>
    ///  Class for testing ThreadsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ThreadsApiTests
    {
        private ThreadsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ThreadsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ThreadsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ThreadsApi
            //Assert.IsInstanceOfType(typeof(ThreadsApi), instance, "instance is a ThreadsApi");
        }

        /// <summary>
        /// Test ArchiveThread
        /// </summary>
        [Test]
        public void ArchiveThreadTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string threadId = null;
            //var response = instance.ArchiveThread(threadId);
            //Assert.IsInstanceOf<Thread> (response, "response is Thread");
        }
        /// <summary>
        /// Test CategorizeThread
        /// </summary>
        [Test]
        public void CategorizeThreadTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string threadId = null;
            //List<string> threadCategoryIds = null;
            //var response = instance.CategorizeThread(threadId, threadCategoryIds);
            //Assert.IsInstanceOf<Thread> (response, "response is Thread");
        }
        /// <summary>
        /// Test CloseThread
        /// </summary>
        [Test]
        public void CloseThreadTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string threadId = null;
            //var response = instance.CloseThread(threadId);
            //Assert.IsInstanceOf<Thread> (response, "response is Thread");
        }
        /// <summary>
        /// Test GetAllThreads
        /// </summary>
        [Test]
        public void GetAllThreadsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? q = null;
            //int? offset = null;
            //int? limit = null;
            //var response = instance.GetAllThreads(q, offset, limit);
            //Assert.IsInstanceOf<GetAllThreadsResponse> (response, "response is GetAllThreadsResponse");
        }
        /// <summary>
        /// Test GetThread
        /// </summary>
        [Test]
        public void GetThreadTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string threadId = null;
            //var response = instance.GetThread(threadId);
            //Assert.IsInstanceOf<Thread> (response, "response is Thread");
        }
        /// <summary>
        /// Test OpenThread
        /// </summary>
        [Test]
        public void OpenThreadTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string threadId = null;
            //var response = instance.OpenThread(threadId);
            //Assert.IsInstanceOf<Thread> (response, "response is Thread");
        }
    }

}
