/* 
 * Engage Digital API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using RingCentral.EngageDigital.Client;
using RingCentral.EngageDigital.Api;
using RingCentral.EngageDigital.Model;

namespace RingCentral.EngageDigital.Test
{
    /// <summary>
    ///  Class for testing CategoriesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class CategoriesApiTests : IDisposable
    {
        private CategoriesApi instance;

        public CategoriesApiTests()
        {
            instance = new CategoriesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CategoriesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' CategoriesApi
            //Assert.IsType(typeof(CategoriesApi), instance, "instance is a CategoriesApi");
        }

        
        /// <summary>
        /// Test CreateCategory
        /// </summary>
        [Fact]
        public void CreateCategoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string parentId = null;
            //int? color = null;
            //bool? mandatory = null;
            //bool? multiple = null;
            //bool? postQualification = null;
            //bool? unselectable = null;
            //Collection<string> sourceIds = null;
            //var response = instance.CreateCategory(name, parentId, color, mandatory, multiple, postQualification, unselectable, sourceIds);
            //Assert.IsType<Category> (response, "response is Category");
        }
        
        /// <summary>
        /// Test DeleteCategory
        /// </summary>
        [Fact]
        public void DeleteCategoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string categoryId = null;
            //string takeOverCategoryId = null;
            //var response = instance.DeleteCategory(categoryId, takeOverCategoryId);
            //Assert.IsType<Category> (response, "response is Category");
        }
        
        /// <summary>
        /// Test GetAllCategories
        /// </summary>
        [Fact]
        public void GetAllCategoriesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string parentId = null;
            //int? offset = null;
            //int? limit = null;
            //var response = instance.GetAllCategories(parentId, offset, limit);
            //Assert.IsType<GetAllCategoriesResponse> (response, "response is GetAllCategoriesResponse");
        }
        
        /// <summary>
        /// Test GetCategory
        /// </summary>
        [Fact]
        public void GetCategoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string categoryId = null;
            //var response = instance.GetCategory(categoryId);
            //Assert.IsType<Category> (response, "response is Category");
        }
        
        /// <summary>
        /// Test UpdateCategory
        /// </summary>
        [Fact]
        public void UpdateCategoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string categoryId = null;
            //string name = null;
            //string parentId = null;
            //int? color = null;
            //bool? mandatory = null;
            //bool? multiple = null;
            //bool? postQualification = null;
            //bool? unselectable = null;
            //Collection<string> sourceIds = null;
            //var response = instance.UpdateCategory(categoryId, name, parentId, color, mandatory, multiple, postQualification, unselectable, sourceIds);
            //Assert.IsType<Category> (response, "response is Category");
        }
        
    }

}
