/* 
 * Engage Digital API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RingCentral.EngageDigital.Api;
using RingCentral.EngageDigital.Model;
using RingCentral.EngageDigital.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RingCentral.Engage.Test
{
    /// <summary>
    ///  Class for testing CustomField
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CustomFieldTests
    {
        // TODO uncomment below to declare an instance variable for CustomField
        //private CustomField instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CustomField
            //instance = new CustomField();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CustomField
        /// </summary>
        [Test]
        public void CustomFieldInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CustomField
            //Assert.IsInstanceOfType<CustomField> (instance, "variable 'instance' is a CustomField");
        }


        /// <summary>
        /// Test the property 'AssociatedTypeName'
        /// </summary>
        [Test]
        public void AssociatedTypeNameTest()
        {
            // TODO unit test for the property 'AssociatedTypeName'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Test]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Test]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }
        /// <summary>
        /// Test the property 'Multiple'
        /// </summary>
        [Test]
        public void MultipleTest()
        {
            // TODO unit test for the property 'Multiple'
        }
        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Test]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

    }

}
