/* 
 * Engage Digital API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RingCentral.EngageDigital.Api;
using RingCentral.EngageDigital.Model;
using RingCentral.EngageDigital.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RingCentral.Engage.Test
{
    /// <summary>
    ///  Class for testing GetAllCommunitiesResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetAllCommunitiesResponseTests
    {
        // TODO uncomment below to declare an instance variable for GetAllCommunitiesResponse
        //private GetAllCommunitiesResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetAllCommunitiesResponse
            //instance = new GetAllCommunitiesResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetAllCommunitiesResponse
        /// </summary>
        [Test]
        public void GetAllCommunitiesResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetAllCommunitiesResponse
            //Assert.IsInstanceOfType<GetAllCommunitiesResponse> (instance, "variable 'instance' is a GetAllCommunitiesResponse");
        }


        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Test]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Test]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }
        /// <summary>
        /// Test the property 'Offset'
        /// </summary>
        [Test]
        public void OffsetTest()
        {
            // TODO unit test for the property 'Offset'
        }
        /// <summary>
        /// Test the property 'Records'
        /// </summary>
        [Test]
        public void RecordsTest()
        {
            // TODO unit test for the property 'Records'
        }

    }

}
