/* 
 * Engage Digital API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RingCentral.EngageDigital.Api;
using RingCentral.EngageDigital.Model;
using RingCentral.EngageDigital.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RingCentral.Engage.Test
{
    /// <summary>
    ///  Class for testing Locale
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LocaleTests
    {
        // TODO uncomment below to declare an instance variable for Locale
        //private Locale instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Locale
            //instance = new Locale();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Locale
        /// </summary>
        [Test]
        public void LocaleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Locale
            //Assert.IsInstanceOfType<Locale> (instance, "variable 'instance' is a Locale");
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Interface'
        /// </summary>
        [Test]
        public void InterfaceTest()
        {
            // TODO unit test for the property 'Interface'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
