/* 
 * Engage Digital API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RingCentral.Engage.Api;
using RingCentral.Engage.Model;
using RingCentral.Engage.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RingCentral.Engage.Test
{
    /// <summary>
    ///  Class for testing Task
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TaskTests
    {
        // TODO uncomment below to declare an instance variable for Task
        //private Task instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Task
            //instance = new Task();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Task
        /// </summary>
        [Test]
        public void TaskInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Task
            //Assert.IsInstanceOfType<Task> (instance, "variable 'instance' is a Task");
        }


        /// <summary>
        /// Test the property 'AcceptedAt'
        /// </summary>
        [Test]
        public void AcceptedAtTest()
        {
            // TODO unit test for the property 'AcceptedAt'
        }
        /// <summary>
        /// Test the property 'AgentIds'
        /// </summary>
        [Test]
        public void AgentIdsTest()
        {
            // TODO unit test for the property 'AgentIds'
        }
        /// <summary>
        /// Test the property 'ChannelId'
        /// </summary>
        [Test]
        public void ChannelIdTest()
        {
            // TODO unit test for the property 'ChannelId'
        }
        /// <summary>
        /// Test the property 'CompletedAt'
        /// </summary>
        [Test]
        public void CompletedAtTest()
        {
            // TODO unit test for the property 'CompletedAt'
        }
        /// <summary>
        /// Test the property 'ContentId'
        /// </summary>
        [Test]
        public void ContentIdTest()
        {
            // TODO unit test for the property 'ContentId'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'ExpireAt'
        /// </summary>
        [Test]
        public void ExpireAtTest()
        {
            // TODO unit test for the property 'ExpireAt'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'InterventionId'
        /// </summary>
        [Test]
        public void InterventionIdTest()
        {
            // TODO unit test for the property 'InterventionId'
        }
        /// <summary>
        /// Test the property 'LockedAt'
        /// </summary>
        [Test]
        public void LockedAtTest()
        {
            // TODO unit test for the property 'LockedAt'
        }
        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Test]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }
        /// <summary>
        /// Test the property 'Step'
        /// </summary>
        [Test]
        public void StepTest()
        {
            // TODO unit test for the property 'Step'
        }
        /// <summary>
        /// Test the property 'ThreadId'
        /// </summary>
        [Test]
        public void ThreadIdTest()
        {
            // TODO unit test for the property 'ThreadId'
        }
        /// <summary>
        /// Test the property 'TransferedAt'
        /// </summary>
        [Test]
        public void TransferedAtTest()
        {
            // TODO unit test for the property 'TransferedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

    }

}
